
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1-node-browsers
    # Add steps to the job
    # See: https://circleci.com/docs/2.0/configuration-reference/#steps
    steps:
      - checkout
      - run:
          name: build dependencies
          command: bundle install
          
      - run:
          name: build the jekyll site
          command: bundle exec jekyll build
          
      - run:
          name: "Print Current time"
          command: date
